name: 'run'

on:
  schedule:
    - cron: '30 */8 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: requirements
        run : pip3 install -r requirements.txt

      - name: main
        env:
          cookie_enshan: ${{ secrets.cookie_enshan }}
        run: |
          sleep $(sh -c 'echo $((1 + RANDOM % 600))')
          python3 ../Enshan/Enshan.py
          
